# Generated by Django 5.0.6 on 2024-08-14 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Grocery_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockx',
            old_name='stock_branch_name',
            new_name='branch_name',
        ),
        migrations.RenameField(
            model_name='stockx',
            old_name='stock_dealer_name',
            new_name='dealer_name',
        ),
    ]
